Replace Triggers with delegate and event for smooth animation.
tuyen-vuduc/todo-app-xamarin-forms pull request #1
Opened 2022-09-09 04:25 UTC by shawyunz

Add delegates and events in two ContentViews.
Remove the triggers in xaml.
Add events invoking and animation in class behind.

2022-09-09 04:30 UTC, tuyen-vuduc commented
@shawyunz It's awesome, thank you very much for your contribution.

2022-09-09 09:49 UTC, shawyunz commented
> @shawyunz It's awesome, thank you very much for your contribution.

Considering to merge it?

2022-09-09 22:35 UTC, tuyen-vuduc commented
> Considering to merge it?

Yes, could you take a look at my comment above?

2022-09-10 09:31 UTC, shawyunz commented
> > Considering to merge it?
> 
> Yes, could you take a look at my comment above?

Emm, sorry, where is that. 
If you mean comment about the code, didn't see your comment in "files changed", you can review there.

2022-09-13 01:49 UTC, tuyen-vuduc requested changes

2022-09-13 01:49 UTC, tuyen-vuduc commented on src/TodoApp/Features/Todos/Pages/TodosPage.xaml.cs
> +            TodoContentView.OnMenuClicked += Menu_Clicked;
Would it be better if we wrap the method inside an EventHandler instance? It'll reduce the coupling.

2022-09-13 01:49 UTC, tuyen-vuduc commented on src/TodoApp/Features/Todos/Pages/TodosPage.xaml.cs
> +            TodoContentView.OnMenuClicked += Menu_Clicked;
@shawyunz Please check my comment here.

2022-09-23 04:08 UTC, shawyunz commented
And community toolkit is another way to do the animation (not tested)
https://learn.microsoft.com/en-us/xamarin/community-toolkit/behaviors/animationbehavior

2022-09-23 04:09 UTC, tuyen-vuduc requested changes

2022-09-23 04:09 UTC, tuyen-vuduc commented on src/TodoApp/Features/Todos/Pages/TodosPage.xaml.cs
> +            TodoContentView.OnMenuClicked += Menu_ClickedEvent;
By creating a new instance of EventHandler to wrap the method, it always uses WeakReference to make things loose coupling. We don't need to add and remove this way.

2022-12-16 22:19 UTC, merged